/**
 * ELITE SEARCH CONFIGURATION
 * ===========================
 * Exhaustive search terms for finding EVERY business in each category.
 * Includes Spanish, English, slang, and every possible variation.
 *
 * The Google Places API is limited - it doesn't have types for photographers,
 * videographers, DJs, chefs, etc. So we MUST use text search with every
 * possible term someone might use.
 */

export const ELITE_SEARCH_TERMS: Record<string, string[]> = {
  photographer: [
    "fotografo bodas",
    "fotógrafo de bodas",
    "fotografo matrimonio",
    "fotografia bodas",
    "fotografía de bodas",
    "fotos de boda",
    "fotografo nupcial",
    "wedding photographer",
    "wedding photography",
    "destination wedding photographer",
    "elopement photographer",
    "engagement photographer",
    "fotografo eventos",
    "fotógrafo de eventos",
    "fotografo profesional",
    "fotógrafo profesional",
    "fotografo fiestas",
    "fotografo corporativo",
    "fotografo empresarial",
    "event photographer",
    "event photography",
    "corporate photographer",
    "party photographer",
    "estudio fotografico",
    "estudio fotográfico",
    "foto estudio",
    "fotografo retratos",
    "sesion de fotos",
    "sesión de fotos",
    "book fotografico",
    "fotografo familiar",
    "photo studio",
    "photography studio",
    "portrait photographer",
    "family photographer",
    "fotografo producto",
    "fotografo comida",
    "fotografo gastronomico",
    "fotografo inmobiliario",
    "fotografo arquitectura",
    "fotografo drone",
    "fotografia aerea",
    "fotografo moda",
    "fotografo quince años",
    "fotografo quinceañera",
    "food photographer",
    "real estate photographer",
    "drone photographer",
    "aerial photography",
    "fashion photographer",
    "commercial photographer",
    "fotografo",
    "fotógrafo",
    "fotografía",
    "photography",
    "photographer",
  ],

  videographer: [
    "videografo bodas",
    "videógrafo de bodas",
    "video bodas",
    "video de bodas",
    "video matrimonio",
    "filmacion bodas",
    "filmación de bodas",
    "cinematografia bodas",
    "pelicula de boda",
    "wedding videographer",
    "wedding videography",
    "wedding filmmaker",
    "wedding cinematographer",
    "wedding film",
    "destination wedding videographer",
    "videografo eventos",
    "videógrafo de eventos",
    "video eventos",
    "filmacion eventos",
    "video corporativo",
    "video empresarial",
    "video institucional",
    "video promocional",
    "event videographer",
    "event videography",
    "corporate video",
    "commercial video",
    "promotional video",
    "productora audiovisual",
    "productora de video",
    "produccion de video",
    "producción de video",
    "casa productora",
    "camarografo",
    "camarógrafo",
    "video production",
    "film production",
    "video producer",
    "filmmaker",
    "cinematographer",
    "video drone",
    "video dron",
    "filmacion aerea",
    "video aereo",
    "drone videographer",
    "aerial videographer",
    "drone video",
    "videografo",
    "videógrafo",
    "videography",
    "videographer",
  ],

  dj: [
    "dj bodas",
    "dj de bodas",
    "dj para bodas",
    "dj matrimonio",
    "musica bodas",
    "música para bodas",
    "sonido bodas",
    "wedding dj",
    "wedding music",
    "destination wedding dj",
    "beach wedding dj",
    "dj eventos",
    "dj de eventos",
    "dj para eventos",
    "dj fiestas",
    "dj para fiestas",
    "dj privado",
    "dj corporativo",
    "dj empresarial",
    "dj cumpleaños",
    "dj quince años",
    "dj quinceañera",
    "event dj",
    "party dj",
    "corporate dj",
    "private event dj",
    "birthday party dj",
    "dj yate",
    "dj barco",
    "dj pool party",
    "dj fiesta piscina",
    "dj despedida soltera",
    "dj despedida soltero",
    "yacht dj",
    "boat party dj",
    "pool party dj",
    "bachelor party dj",
    "bachelorette party dj",
    "sonido eventos",
    "sonido para eventos",
    "sonido fiestas",
    "alquiler sonido",
    "alquiler de sonido",
    "disco movil",
    "discoteca movil",
    "audio eventos",
    "iluminacion eventos",
    "alquiler luces",
    "sound system rental",
    "audio equipment rental",
    "event lighting",
    "mobile disco",
    "musica en vivo",
    "música en vivo",
    "musica para eventos",
    "animador fiestas",
    "animacion eventos",
    "entretenimiento eventos",
    "grupo musical",
    "banda para eventos",
    "mariachi",
    "vallenato",
    "orquesta",
    "live music",
    "live band",
    "musicians for hire",
    "entertainment services",
    "dj",
    "disc jockey",
    "deejay",
    "dj profesional",
  ],

  chef: [
    "chef privado",
    "chef a domicilio",
    "chef en casa",
    "chef personal",
    "cocinero privado",
    "cocinero a domicilio",
    "servicio de chef",
    "chef para eventos",
    "chef para fiestas",
    "private chef",
    "personal chef",
    "chef at home",
    "home chef",
    "hire a chef",
    "chef for hire",
    "chef para villa",
    "chef villa",
    "chef vacaciones",
    "chef airbnb",
    "chef finca",
    "chef yate",
    "chef barco",
    "villa chef",
    "vacation chef",
    "yacht chef",
    "boat chef",
    "catering",
    "servicio catering",
    "catering eventos",
    "catering bodas",
    "catering empresarial",
    "catering corporativo",
    "banquetes",
    "servicio banquetes",
    "banquetero",
    "catering service",
    "event catering",
    "wedding catering",
    "corporate catering",
    "party catering",
    "cena privada",
    "cenas privadas",
    "cena romantica",
    "cena romántica",
    "cena en casa",
    "experiencia gastronomica",
    "experiencia gastronómica",
    "degustacion",
    "menu degustacion",
    "cocina gourmet",
    "alta cocina",
    "private dinner",
    "romantic dinner",
    "dining experience",
    "gourmet experience",
    "tasting menu",
    "parrillero",
    "asador privado",
    "bbq privado",
    "asado privado",
    "chef sushi",
    "sushi chef",
    "chef ceviche",
    "chef mariscos",
    "pastelero",
    "repostero",
    "bbq chef",
    "grill master",
    "pastry chef",
    "chef",
    "cocinero",
    "gastronomia",
    "clase de cocina",
    "clases de cocina",
    "cooking class",
  ],

  event_planner: [
    "wedding planner",
    "organizador de bodas",
    "organizadora de bodas",
    "planificador de bodas",
    "planificadora de bodas",
    "coordinador de bodas",
    "coordinadora de bodas",
    "bodas destino",
    "bodas en la playa",
    "bodas cartagena",
    "wedding coordinator",
    "wedding organizer",
    "destination wedding planner",
    "beach wedding planner",
    "luxury wedding planner",
    "elopement planner",
    "organizador de eventos",
    "organizadora de eventos",
    "planificador de eventos",
    "planificadora de eventos",
    "coordinador de eventos",
    "eventos corporativos",
    "eventos empresariales",
    "produccion de eventos",
    "event planner",
    "event coordinator",
    "event organizer",
    "corporate event planner",
    "conference planner",
    "event planning",
    "decoracion de eventos",
    "decoración de eventos",
    "decorador de eventos",
    "ambientacion eventos",
    "montaje eventos",
    "event decorator",
    "event design",
    "party planner",
    "party decorator",
    "planificador quince años",
    "quinceañera planner",
    "baby shower planner",
    "cumpleaños",
    "fiestas infantiles",
    "birthday party planner",
    "kids party planner",
    "florista eventos",
    "flores para eventos",
    "flores para bodas",
    "event florist",
    "wedding florist",
    "floral designer",
    "arreglos florales",
  ],

  hotel: [
    "hotel boutique",
    "hotel de lujo",
    "hotel 5 estrellas",
    "hotel colonial",
    "hotel centro historico",
    "hotel centro histórico",
    "boutique hotel",
    "luxury hotel",
    "5 star hotel",
    "historic hotel",
    "heritage hotel",
    "hotel spa",
    "resort spa",
    "eco hotel",
    "eco lodge",
    "adults only hotel",
    "hotel adultos",
    "romantic hotel",
    "honeymoon hotel",
    "hotel luna de miel",
    "posada",
    "hosteria",
    "hostal boutique",
    "casa hotel",
    "hacienda hotel",
    "finca hotel",
    "hotel hacienda",
    "hotel finca",
    "hotel campestre",
    "country hotel",
    "beach hotel",
    "hotel playa",
    "oceanfront hotel",
    "hotel frente al mar",
    "all inclusive",
    "todo incluido",
    "resort",
    "hotel resort",
    "hotel cartagena",
    "hotel medellin",
    "hotel bogota",
    "hotel getsemani",
    "hotel bocagrande",
    "hotel ciudad amurallada",
    "hotel walled city",
    "hotel centro",
    "lodging",
    "accommodation",
    "hospedaje",
    "alojamiento",
  ],

  boat_charter: [
    "alquiler de yate",
    "alquiler yate",
    "renta de yate",
    "yate privado",
    "yacht charter",
    "yacht rental",
    "private yacht",
    "luxury yacht",
    "yate de lujo",
    "alquiler de lancha",
    "renta de lancha",
    "lancha privada",
    "boat rental",
    "boat charter",
    "private boat",
    "speedboat rental",
    "catamaran",
    "catamarán",
    "alquiler catamaran",
    "velero",
    "sailboat rental",
    "sailing charter",
    "tour en bote",
    "tour en yate",
    "paseo en bote",
    "paseo en lancha",
    "boat tour",
    "yacht tour",
    "islas del rosario",
    "tour islas",
    "island tour",
    "sunset cruise",
    "crucero atardecer",
    "fiesta en yate",
    "fiesta en barco",
    "yacht party",
    "boat party",
    "pesca deportiva",
    "fishing charter",
    "deep sea fishing",
    "sport fishing",
    "snorkel tour",
    "diving tour",
    "buceo",
    "marina",
    "puerto deportivo",
    "jet ski",
    "moto acuatica",
    "water sports",
    "deportes acuaticos",
  ],

  villa_rental: [
    "villa privada",
    "villa de lujo",
    "villa vacacional",
    "alquiler villa",
    "renta de villa",
    "private villa",
    "luxury villa",
    "vacation villa",
    "villa rental",
    "villa cartagena",
    "casa vacacional",
    "casa de lujo",
    "alquiler casa lujo",
    "vacation home",
    "luxury home rental",
    "holiday rental",
    "finca de lujo",
    "finca privada",
    "alquiler finca",
    "luxury finca",
    "country estate",
    "hacienda",
    "casona",
    "mansion",
    "mansión",
    "estate rental",
    "penthouse",
    "apartamento de lujo",
    "luxury apartment",
    "airbnb lujo",
    "airbnb luxury",
    "vrbo",
    "casa en la playa",
    "beach house",
    "oceanfront villa",
    "villa frente al mar",
    "casa piscina",
    "pool villa",
    "villa con piscina",
    "property management",
    "administracion propiedades",
    "vacation rental",
    "short term rental",
    "alquiler temporal",
  ],

  concierge: [
    "servicio concierge",
    "concierge privado",
    "concierge de lujo",
    "concierge service",
    "luxury concierge",
    "private concierge",
    "lifestyle management",
    "personal assistant",
    "asistente personal",
    "mayordomo",
    "butler service",
    "vip services",
    "servicios vip",
    "experiencias lujo",
    "luxury experiences",
    "bespoke travel",
    "viajes personalizados",
    "travel planner",
    "trip planner",
    "planificador viajes",
    "destination management",
    "dmc",
    "receptivo turistico",
    "incoming travel",
    "fixer",
    "local guide",
    "guia local",
    "private tour",
    "tour privado",
    "exclusive experiences",
    "experiencias exclusivas",
    "reservaciones vip",
    "vip reservations",
    "restaurant reservations",
    "reservas restaurantes",
    "nightlife concierge",
    "club access",
    "acceso clubs",
    "event tickets",
    "entradas eventos",
    "helicopter tour",
    "tour helicoptero",
    "private jet",
    "jet privado",
  ],

  transportation: [
    "transporte ejecutivo",
    "transporte de lujo",
    "transporte vip",
    "executive transportation",
    "luxury transportation",
    "vip transportation",
    "limusina",
    "limousine",
    "limo service",
    "servicio limusina",
    "chofer privado",
    "conductor privado",
    "private driver",
    "private chauffeur",
    "chauffeur service",
    "alquiler de auto",
    "renta de auto",
    "car rental",
    "luxury car rental",
    "auto de lujo",
    "alquiler auto lujo",
    "suv rental",
    "van rental",
    "sprinter rental",
    "transfer aeropuerto",
    "airport transfer",
    "airport pickup",
    "traslado aeropuerto",
    "shuttle service",
    "ground transportation",
    "transporte terrestre",
    "wedding transportation",
    "transporte bodas",
    "party bus",
    "bus de fiesta",
    "grupo transporte",
    "group transportation",
    "corporate transportation",
    "transporte corporativo",
    "taxi ejecutivo",
    "executive taxi",
    "uber black",
    "cabify",
    "vintage car",
    "carro clasico",
    "classic car rental",
  ],

  coworking: [
    "coworking",
    "espacio coworking",
    "oficina compartida",
    "coworking space",
    "shared office",
    "flexible workspace",
    "hot desk",
    "desk rental",
    "alquiler escritorio",
    "oficina virtual",
    "virtual office",
    "business center",
    "centro de negocios",
    "meeting room",
    "sala de reuniones",
    "conference room",
    "sala de conferencias",
    "private office",
    "oficina privada",
    "startup hub",
    "incubadora",
    "accelerator",
    "workspace",
    "espacio de trabajo",
    "oficina por hora",
    "hourly office",
    "day office",
    "work cafe",
    "cafe trabajo",
  ],
};

export const TEXT_SEARCH_ONLY_CATEGORIES = [
  "photographer",
  "videographer",
  "dj",
  "chef",
  "event_planner",
  "boat_charter",
  "villa_rental",
  "concierge",
  "transportation",
  "coworking",
];

export const CITY_COORDINATES: Record<string, { lat: number; lng: number; radius: number; neighborhoods?: Array<{ name: string; lat: number; lng: number; radius: number }> }> = {
  cartagena: {
    lat: 10.3910,
    lng: -75.4794,
    radius: 15000,
    neighborhoods: [
      { name: "Centro Histórico", lat: 10.4236, lng: -75.5503, radius: 2000 },
      { name: "Getsemaní", lat: 10.4195, lng: -75.5485, radius: 1500 },
      { name: "Bocagrande", lat: 10.3988, lng: -75.5565, radius: 3000 },
      { name: "Castillogrande", lat: 10.3878, lng: -75.5598, radius: 2000 },
      { name: "Manga", lat: 10.4098, lng: -75.5405, radius: 2000 },
      { name: "La Boquilla", lat: 10.4682, lng: -75.5107, radius: 3000 },
    ],
  },
  medellin: {
    lat: 6.2442,
    lng: -75.5812,
    radius: 20000,
    neighborhoods: [
      { name: "El Poblado", lat: 6.2086, lng: -75.5659, radius: 4000 },
      { name: "Laureles", lat: 6.2456, lng: -75.5917, radius: 3000 },
      { name: "Envigado", lat: 6.1714, lng: -75.5873, radius: 4000 },
      { name: "Centro", lat: 6.2518, lng: -75.5636, radius: 2000 },
    ],
  },
  bogota: {
    lat: 4.7110,
    lng: -74.0721,
    radius: 25000,
    neighborhoods: [
      { name: "Zona G", lat: 4.6686, lng: -74.0551, radius: 2000 },
      { name: "Zona T", lat: 4.6666, lng: -74.0527, radius: 2000 },
      { name: "Usaquén", lat: 4.6955, lng: -74.0323, radius: 3000 },
      { name: "Chapinero", lat: 4.6425, lng: -74.0628, radius: 3000 },
      { name: "La Candelaria", lat: 4.5964, lng: -74.0734, radius: 2000 },
    ],
  },
  cali: {
    lat: 3.4516,
    lng: -76.5320,
    radius: 18000,
  },
  barranquilla: {
    lat: 10.9685,
    lng: -74.7813,
    radius: 15000,
  },
  "santa marta": {
    lat: 11.2404,
    lng: -74.2110,
    radius: 12000,
    neighborhoods: [
      { name: "Rodadero", lat: 11.2053, lng: -74.2285, radius: 3000 },
      { name: "Centro Histórico", lat: 11.2448, lng: -74.2081, radius: 2000 },
      { name: "Taganga", lat: 11.2660, lng: -74.1917, radius: 2000 },
    ],
  },
  "san andres": {
    lat: 12.5847,
    lng: -81.7006,
    radius: 8000,
  },
  bucaramanga: {
    lat: 7.1193,
    lng: -73.1227,
    radius: 12000,
  },
  pereira: {
    lat: 4.8087,
    lng: -75.6906,
    radius: 10000,
  },
};

export const ELITE_SEARCH_CONFIG = {
  maxResultsPerTerm: 20,
  delayBetweenCalls: 200,
  maxConcurrentRequests: 3,
  includeNeighborhoods: true,
};
