"""Service modules for data processing and storage."""
from .enricher import AIEnricher, generate_outreach_email
from .storage import SupabaseStorage
from .exporter import Exporter
from .outreach import OutreachGenerator, format_audit_markdown, VERTICAL_INTELLIGENCE
from .deep_scan import (
    DeepScanEngine,
    BusinessDeepScan,
    run_deep_scan,
    run_batch_deep_scan,
    VERTICAL_DEEP_INTEL,
    CITY_PRIORITIES,
    PHIL_VOICE,
)
from .transformation import (
    TransformationPlan,
    generate_transformation_plan,
    format_plan_markdown,
    format_plan_html,
)
from .authority_content import (
    AuthorityContentGenerator,
    ContentPiece,
    generate_content_batch,
)
from .sales_psychology import (
    get_psychology_framework,
    get_credentials_statement,
    FRAMEWORK_CREDENTIALS,
    NEUROSCIENCE_NLP,
    BEHAVIORAL_ECONOMICS,
    IDENTITY_TRANSFORMATION,
    COMPLIANCE_PSYCHOLOGY,
    INTEGRATED_OUTREACH,
    PAIN_AMPLIFIERS,
)
from .outreach_ready import (
    OutreachReadyExporter,
    export_outreach_ready,
    generate_wa_link,
    generate_ig_link,
    CHANNEL_STRATEGY,
)
from .ultimate_outreach import (
    BusinessIntelligence,
    InstagramProfile,
    generate_business_intelligence,
    discover_instagram,
    determine_offer,
    export_to_csv,
    export_to_html_dashboard,
    process_batch,
    OFFER_MATRIX,
)
from .colombia_market_intel import (
    generate_colombia_market_intel,
    generate_colombia_pitch,
    detect_tech_stack_gaps,
    COLOMBIA_STATS,
    CONPES_POSITIONING,
    COLOMBIA_PSYCHOLOGY_TRIGGERS,
    VERTICAL_TICKET_RANGES,
    FUNDING_PATHWAYS,
    COLOMBIA_COMPETITORS,
    get_whatsapp_stat_hook,
    get_tourist_volume_hook,
    get_abandon_rate_hook,
    get_ai_adoption_hook,
    get_funding_pitch,
    ColombiaMarketIntel,
    TechStackGaps,
)
from .black_card_vault import (
    generate_black_card_intelligence,
    generate_colombia_enhanced_intelligence,
    BlackCardIntelligence,
    CATEGORY_SOLUTIONS,
)

__all__ = [
    "AIEnricher",
    "generate_outreach_email",
    "SupabaseStorage",
    "Exporter",
    "OutreachGenerator",
    "format_audit_markdown",
    "VERTICAL_INTELLIGENCE",
    "DeepScanEngine",
    "BusinessDeepScan",
    "run_deep_scan",
    "run_batch_deep_scan",
    "VERTICAL_DEEP_INTEL",
    "CITY_PRIORITIES",
    "PHIL_VOICE",
    "TransformationPlan",
    "generate_transformation_plan",
    "format_plan_markdown",
    "format_plan_html",
    "AuthorityContentGenerator",
    "ContentPiece",
    "generate_content_batch",
    "get_psychology_framework",
    "get_credentials_statement",
    "FRAMEWORK_CREDENTIALS",
    "NEUROSCIENCE_NLP",
    "BEHAVIORAL_ECONOMICS",
    "IDENTITY_TRANSFORMATION",
    "COMPLIANCE_PSYCHOLOGY",
    "INTEGRATED_OUTREACH",
    "PAIN_AMPLIFIERS",
    "OutreachReadyExporter",
    "export_outreach_ready",
    "generate_wa_link",
    "generate_ig_link",
    "CHANNEL_STRATEGY",
    # Ultimate Outreach System
    "BusinessIntelligence",
    "InstagramProfile",
    "generate_business_intelligence",
    "discover_instagram",
    "determine_offer",
    "export_to_csv",
    "export_to_html_dashboard",
    "process_batch",
    "OFFER_MATRIX",
    # Colombia Market Intelligence
    "generate_colombia_market_intel",
    "generate_colombia_pitch",
    "detect_tech_stack_gaps",
    "COLOMBIA_STATS",
    "CONPES_POSITIONING",
    "COLOMBIA_PSYCHOLOGY_TRIGGERS",
    "VERTICAL_TICKET_RANGES",
    "FUNDING_PATHWAYS",
    "COLOMBIA_COMPETITORS",
    "get_whatsapp_stat_hook",
    "get_tourist_volume_hook",
    "get_abandon_rate_hook",
    "get_ai_adoption_hook",
    "get_funding_pitch",
    "ColombiaMarketIntel",
    "TechStackGaps",
    # Black Card Vault
    "generate_black_card_intelligence",
    "generate_colombia_enhanced_intelligence",
    "BlackCardIntelligence",
    "CATEGORY_SOLUTIONS",
]
